// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by generate-protos. DO NOT EDIT.

package genid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

const File_system_couchbase_afkey_proto = "system/couchbase/afKey.proto"

// Names for google.protobuf.FieldMask.
const (
	AFKey_package     protoreflect.FullName     = "com.onewealthplace.airdistrib.system.couchbase"
	AFKey_message_name     protoreflect.Name     = "AFKey"
	AFKey_message_fullname protoreflect.FullName = "com.onewealthplace.airdistrib.system.couchbase.AFKey"
)

// Field names for google.protobuf.FieldMask.
const (
	AFKey_Id_field_name protoreflect.Name = "id"

	AFKey_Id_field_fullname protoreflect.FullName = "com.onewealthplace.airdistrib.system.couchbase.AFKey.id"
)

// Field numbers for google.protobuf.FieldMask.
const (
	AFKey_Id_field_number protoreflect.FieldNumber = 1
)
