// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by generate-protos. DO NOT EDIT.

package genid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

const File_system_mongo_objectid_proto = "system/mongo/objectid.proto"

// Names for google.protobuf.FieldMask.
const (
	ObjectId_package     protoreflect.FullName     = "com.onewealthplace.airdistrib.system.mongo"
	ObjectId_message_name     protoreflect.Name     = "ObjectId"
	ObjectId_message_fullname protoreflect.FullName = "com.onewealthplace.airdistrib.system.mongo.ObjectId"
)

// Field names for google.protobuf.FieldMask.
const (
	ObjectId_Value_field_name protoreflect.Name = "value"

	ObjectId_Value_field_fullname protoreflect.FullName = "com.onewealthplace.airdistrib.system.mongo.ObjectId.value"
)

// Field numbers for google.protobuf.FieldMask.
const (
	ObjectId_Value_field_number protoreflect.FieldNumber = 1
)
